server:
  servlet:
    context-path: /redisson
  port: 21007
  undertow:
  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io-threads: 4
      # 阻塞任务线程池
      worker-threads: 50
      buffer-size: 512
      direct-buffers: true
spring:
  application:
      name: example-redisson
#  main:
#    allow-bean-definition-overriding: true  #redis 配置
  redis:
    #数据库索引
    database: 0
    #   host: 127.0.0.1
    host: 47.93.101.163
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

  session:
    store-type: redis
    timeout: 2000
#    redis:
#      namespace: example_namespace