server:
  port: 21008
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池
    worker-threads: 50
    buffer-size: 512
    direct-buffers: true

spring:
  application:
    name: example-controller
  main:
    allow-bean-definition-overriding: true
  servlet:
    # 文件上传
    multipart:
      # 上传文件的临时目录 （linux的默认临时目录定时会被删除会导致上传失败，尽量指定临时目录）
      location: /data/tmp
      # 是否支持批量上传   (默认值 true)
      enabled: true
      # 上传文件最大为 1M （默认值 1M 根据自身业务自行控制即可）
      max-file-size: 1MB
      # 设置总上传的数据大小 10M（默认值10M 根据自身业务自行控制即可）
      max-request-size: 1MB
      # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      file-size-threshold: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    #熔断启动
    enabled: true
  client:
    config:
      default:
        #超时时间 (ms)
        connectTimeout: 20000
        readTimeout: 20000
# 将线程隔离设置为SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 9000

##服务地址:
server-feign-name:
  order: example-client
