server:
  port: 21008
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池
    worker-threads: 50
    buffer-size: 512
    direct-buffers: true

spring:
  application:
    name: example-controller
  main:
    allow-bean-definition-overriding: true
  servlet:
    # 文件上传
    multipart:
      # 上传文件的临时目录 （linux的默认临时目录定时会被删除会导致上传失败，尽量指定临时目录）
      location: /data/tmp
      # 是否支持批量上传   (默认值 true)
      enabled: true
      # 上传文件最大为 1M （默认值 1M 根据自身业务自行控制即可）
      max-file-size: 1MB
      # 设置总上传的数据大小 10M（默认值10M 根据自身业务自行控制即可）
      max-request-size: 1MB
      # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      file-size-threshold: 0


eureka:
  instance:
    prefer-ip-address: true
    # 设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 3
    # 如果现在超过了5秒的间隔
    lease-expiration-duration-in-seconds: 9
  client:
    register-with-eureka: true
    fetch-registry: true
    # #CacherefreshThread线程的调度频率，eureka默认30秒刷新一次缓存
    registry-fetch-interval-seconds: 10
    #刷新Eureka Server地址的时间间隔
    eureka-service-url-poll-interval-seconds: 300
    #instanceInfoReplication将实例信息变更同步到Eureka Server的初始延时时间，默认40秒
    initial-instance-info-replication-interval-seconds: 40
    #InstanceInfoReplication将实例信息变更同步到Eureka Server的时间间隔
    instance-info-replication-interval-seconds: 30
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/